# Generated by Django 4.0.5 on 2022-10-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
