# Generated by Django 4.1.2 on 2022-10-25 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0006_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                null=True, related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
