# Generated by Django 4.1.2 on 2022-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_event_end_time_event_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="booked_seate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
