# Generated by Django 4.1.2 on 2022-10-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_event_booked_seate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="booked_seate",
            new_name="book_seats",
        ),
    ]
