# Generated by Django 4.1.2 on 2022-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_rename_booked_seate_event_book_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
    ]
